install:
  cache:
    prepared_shop: false
  git:
    repository: 'fresh-advance/electronic-invoice'
    ref: &ref '{{ .Github.RefName }}'
    shop_url: 'https://github.com/Fresh-Advance/Electronic-Invoice'
    shop_ref: *ref
  composer:
    root_url: ''
    transform: |
      {
          "require": {
              "oxid-esales/oxideshop-ce": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/twig-component": "{{ .Data.install.composer.dev_ref }}",
              "oxid-esales/twig-admin-theme": "{{ .Data.global.composer.dev_ref }}",
              "oxid-esales/apex-theme": "{{ .Data.global.composer.dev_ref }}",
              "symfony/filesystem": "v6.4.13"
          }
      }
  custom_script_container: |
    vendor/bin/oe-console oe:database:reset --db-host=mysql --db-port=3306 --db-name=example --db-user=root --db-password=root --force
    vendor/bin/oe-console oe:module:install ./
    vendor/bin/oe-eshop-doctrine_migration migrations:migrate
    vendor/bin/oe-console oe:module:activate fa_invoice
    vendor/bin/oe-console oe:module:activate fa_electronic_invoice
    vendor/bin/oe-console oe:theme:activate apex

install_shop_with_modules:
  composer:
    root_url: ''

runscript: &runscript
  matrix:
    script: |
      [
        "module_electronic_invoice:tests-unit",
        "module_electronic_invoice:tests-integration",
        "module_electronic_invoice:tests-codeception"
      ]
  module_electronic_invoice:
    path: ''

runslim:
  <<: *runscript
  matrix:
    script: |
      [
        "module_electronic_invoice:phpcs-report",
        "module_electronic_invoice:phpmd-report",
        "module_electronic_invoice:phpstan-report"
      ]

sonarcloud:
  matrix:
    testplan: '["-"]'
  strip_path: '/var/www/'
  project_key: 'Fresh-Advance_Electronic-Invoice'
  project_name: 'Electronic-Invoice'
  organization: 'fresh-advance'
  parameters: |
    -Dsonar.language=php \
    -Dsonar.scm.provider=git \
    -Dsonar.sources=src \
    -Dsonar.tests=tests \
    -Dsonar.php.phpstan.reportPaths=coverage-reports/phpstan.report.json
