imports:
  - { resource: BuilderConfigurator/services.yaml }

services:
  _defaults:
    public: false
    autowire: true

  FreshAdvance\ElectronicInvoice\ZUGFeRD\InvoiceGeneratorDecorator:
    decorates: FreshAdvance\Invoice\Pdf\InvoiceGeneratorInterface
    arguments:
      $originalInvoiceGenerator: '@.inner'

  FreshAdvance\ElectronicInvoice\ZUGFeRD\Factory\ZugferdXmlBuilderFactoryInterface:
    class: FreshAdvance\ElectronicInvoice\ZUGFeRD\Factory\ZugferdXmlBuilderFactory

  FreshAdvance\ElectronicInvoice\ZUGFeRD\Service\ZugferdXmlBuilderInterface:
    class: FreshAdvance\ElectronicInvoice\ZUGFeRD\Service\ZugferdXmlBuilder

  FreshAdvance\ElectronicInvoice\ZUGFeRD\Factory\ZugferdPdfMergerFactoryInterface:
    class: FreshAdvance\ElectronicInvoice\ZUGFeRD\Factory\ZugferdPdfMergerFactory

  FreshAdvance\ElectronicInvoice\ZUGFeRD\Service\ZugferdPdfMergerInterface:
    class: FreshAdvance\ElectronicInvoice\ZUGFeRD\Service\ZugferdPdfMerger
